### ISSUE TITLE
 index out of bounds error

### ISSUE THREAD

**Issue by seoanezonjic** [PGScatalog/pgsc_calc#107]
### Description of the bug

I have the following error:
`pyo3_runtime.PanicException: index out of bounds: the len is 0 but the index is 0`
I have not idea which causes this  error. Maybe something is wrong in my vcf files?

Thank you in advance
Pedro Seoane

### Command used and terminal output

```console
nextflow run pgscatalog/pgsc_calc -profile conda --pgs_id PGS000010,PGS000011 --target_build GRCh38 --input samplelist.csv -c custom.config

custom.config:
process {
    executor = 'local'

    withLabel:process_low {
        cpus   = 1
        memory = 8.GB
        time   = 4.h
    }
    withLabel:process_medium {
        cpus   = 1
        memory = 64.GB
        time   = 40.h
    }
    withName: PLINK2_SCORE {
        maxForks = 4
    }
}

Output:

Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:MATCH_COMBINE (BP_6)'

Caused by:
  Process `PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:MATCH_COMBINE (BP_6)` terminated with an error exit status (1)

Command executed:

  export POLARS_MAX_THREADS=1

  combine_matches                  --dataset BP_6         --scorefile scorefiles.txt.gz         --matches *.ipc.zst         -n 1         --min_overlap 0.75                           --outdir $PWD                  -v

  cat <<-END_VERSIONS > versions.yml
  MATCH_COMBINE:
      pgscatalog_utils: $(echo $(python -c 'import pgscatalog_utils; print(pgscatalog_utils.__version__)'))
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  root: 2023-05-26 16:05:29 DEBUG    Verbose logging enabled
  pgscatalog_utils.config: 2023-05-26 16:05:29 DEBUG    Using 1 threads to read CSVs
  pgscatalog_utils.config: 2023-05-26 16:05:29 DEBUG    polars threadpool size: 1
  pgscatalog_utils.match.read: 2023-05-26 16:05:29 DEBUG    Reading scorefile
  pgscatalog_utils.match.read: 2023-05-26 16:05:29 DEBUG    --chrom parameter not set, using all variants in scoring file
  pgscatalog_utils.match.preprocess: 2023-05-26 16:05:29 DEBUG    Complementing column effect_allele
  pgscatalog_utils.match.preprocess: 2023-05-26 16:05:29 DEBUG    Complementing column other_allele
  pgscatalog_utils.match.combine_matches: 2023-05-26 16:05:29 DEBUG    Reading matches
  pgscatalog_utils.match.combine_matches: 2023-05-26 16:05:29 DEBUG    Labelling match candidates
  pgscatalog_utils.match.label: 2023-05-26 16:05:29 DEBUG    Labelling best match type (refalt > altref > ...)
  pgscatalog_utils.match.label: 2023-05-26 16:05:29 DEBUG    Labelling duplicated best match: keeping first instance as best_match = True
  pgscatalog_utils.match.label: 2023-05-26 16:05:29 DEBUG    Labelling multiple scoring file lines (accession/row_nr) that best_match to the same variant
  pgscatalog_utils.match.label: 2023-05-26 16:05:29 DEBUG    Labelling all duplicates with exclude flag
  pgscatalog_utils.match.label: 2023-05-26 16:05:29 DEBUG    Labelling ambiguous variants
  pgscatalog_utils.match.preprocess: 2023-05-26 16:05:29 DEBUG    Complementing column REF
  pgscatalog_utils.match.label: 2023-05-26 16:05:29 DEBUG    Labelling ambiguous variants with exclude flag
  pgscatalog_utils.match.label: 2023-05-26 16:05:29 DEBUG    Labelling multiallelic matches with exclude flag
  pgscatalog_utils.match.label: 2023-05-26 16:05:29 DEBUG    Not excluding flipped matches
  thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/runner/work/polars/polars/polars/polars-core/src/frame/hash_join/single_keys_left.rs:54:23
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  Traceback (most recent call last):
    File "/mnt/home/users/pab_001_uma/pedro/test/pgs_calc/work/conda/pgscatalog_utils-a53cf20bfeebc9debea8741fa1be2fea/bin/combine_matches", line 8, in <module>
      sys.exit(combine_matches())
    File "/mnt/home/users/pab_001_uma/pedro/test/pgs_calc/work/conda/pgscatalog_utils-a53cf20bfeebc9debea8741fa1be2fea/lib/python3.10/site-packages/pgscatalog_utils/match/combine_matches.py", line 33, in combine_matches
      _check_duplicate_vars(matches)
    File "/mnt/home/users/pab_001_uma/pedro/test/pgs_calc/work/conda/pgscatalog_utils-a53cf20bfeebc9debea8741fa1be2fea/lib/python3.10/site-packages/pgscatalog_utils/match/combine_matches.py", line 45, in _check_duplicate_vars
      .collect()
    File "/mnt/home/users/pab_001_uma/pedro/test/pgs_calc/work/conda/pgscatalog_utils-a53cf20bfeebc9debea8741fa1be2fea/lib/python3.10/site-packages/polars/internals/lazyframe/frame.py", line 1045, in collect
      return pli.wrap_df(ldf.collect())
  pyo3_runtime.PanicException: index out of bounds: the len is 0 but the index is 0

Work dir:
  /mnt/home/users/pab_001_uma/pedro/test/pgs_calc/work/0e/c5523cd15f14a95cec19ca2d620214

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
ERROR: No scores calculated!
```
```


### Relevant files

_No response_

### System information

_No response_

**Comment by nebfield** [comment]
Thanks for reporting the bug. This is quite a low level bug so it's difficult to diagnose:

```
pgsc_calc <- you're here
└── pgscatalog_utils (our python package)
    └── polars (a python library we use and love)
        └── rust <- (where the error occurs)
```

Could you test the workflow with either the `docker` or `singularity` profiles? It would be interesting to see if it's reproducible. The `conda` profile sometimes causes problems with local system set ups.
