### ISSUE TITLE
test profile not working

### ISSUE THREAD

**Issue by staedlern** [PGScatalog/pgsc_calc#151]
### Description of the bug

I have previously used successfully pgsc_calc. I now tried the latest version of pgsc_calc and followed the steps in pgsc_calc documentation. Unfortunately I get an error when executing the test profile with:  nextflow run pgscatalog/pgsc_calc -profile test,singularity
I have not find any information on the error messages. Your help would be highly appreciated. Thank you!

### Command used and terminal output

```console
$ nextflow run pgscatalog/pgsc_calc -profile test,singularity

> ERROR ~ Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)'
> 
> Caused by:
>   Process `PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)` terminated with an error exit status (1)
> 
> Command executed:
> 
>   samplesheet_to_json samplesheet.csv out.json
>   
>   cat <<-END_VERSIONS > versions.yml
>   SAMPLESHEET_JSON:
>       python: $(echo $(python --version 2>&1) | cut -f 2 -d ' ')
>   END_VERSIONS
> 
> Command exit status:
>   1
> 
> Command output:
>   (empty)
> Command error:
>   pgscatalog_utils.samplesheet.check: 2023-08-10 12:09:37 WARNING  Relative path detected in samplesheet. Set absolute paths to silence this warning.
>   pgscatalog_utils.samplesheet.check: 2023-08-10 12:09:37 WARNING  Assuming program working directory is a nextflow work directory (e.g. work/4c/8585/...)
>   pgscatalog_utils.samplesheet.check: 2023-08-10 12:09:37 WARNING  Resolving paths relative to work directory parent /gpfs/scratchfs01/site/u/staedlen/GRACE/pgs
>   pgscatalog_utils.samplesheet.check: 2023-08-10 12:09:37 CRITICAL /gpfs/scratchfs01/site/u/staedlen/pgs/assets/examples/target_genomes/cineca_synthetic_subset.pgen doesn't exist, please check samplesheet 
> path_prefix and try again
>   Traceback (most recent call last):
>     File "/venv/bin/samplesheet_to_json", line 8, in <module>
>       sys.exit(check_samplesheet())
>     File "/venv/lib/python3.10/site-packages/pgscatalog_utils/samplesheet/check.py", line 276, in check_samplesheet
>       df = _setup_paths(df)
>     File "/venv/lib/python3.10/site-packages/pgscatalog_utils/samplesheet/check.py", line 152, in _setup_paths
>       resolved_paths: list[str] = _resolve_paths([row['path_prefix'] + x for x in suffix], row['format'])
>     File "/venv/lib/python3.10/site-packages/pgscatalog_utils/samplesheet/check.py", line 209, in _resolve_paths
>       raise FileNotFoundError
>   FileNotFoundError
> 
> Work dir:
>   /gpfs/scratchfs01/site/u/staedlen/GRACE/pgs/work/71/2b6af6fa204111fdaea37f40044e0e
> 
> Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
> 
>  -- Check '.nextflow.log' file for details
> ERROR ~ ERROR: Matching subworkflow failed
> 
>  -- Check '.nextflow.log' file for details
> ERROR ~ ERROR: No scores calculated!
> 
>  -- Check '.nextflow.log' file for details
> ERROR ~ ERROR: No results report written!
> 
>  -- Check '.nextflow.log' file for details
```

### System information

N E X T F L O W  ~  version 23.04.1 
pgscatalog/pgsc_calc v2.0.0
HPC

**Comment by smlmbrt** [comment]
Hi @staedlern, version 2 has a breaking change that requires you to make a new samplesheet in a slightly different format (less wide): https://pgsc-calc.readthedocs.io/en/latest/how-to/samplesheet.html

@nebfield maybe we could add a check/error message if we think it's in the old format?

**Comment by nebfield** [comment]
It might be a good idea to delete the older version of the calculator. Try `rm -r $HOME/.nextflow/assets` and then re-run the test profile.

**Comment by staedlern** [comment]
Hi @smlmbrt @nebfield, the error occurs when running the test profile. Can it be that the test profile includes the old sample file format? I did delete the .nextflow folder prior to running the test. Thx for your help!

**Comment by nebfield** [comment]
Ah, I understand the problem now. All of our tests use a cloned copy of the repository, where the test profile works OK. Could you please test cloning the repository:

```
$ git clone https://github.com/PGScatalog/pgsc_calc.git
$ cd pgsc_calc
$ nextflow run main.nf -profile test,singularity 
```
