### ISSUE TITLE
Launch directory dependent FileNotFound

### ISSUE THREAD

**Issue by alkaZeltser** [PGScatalog/pgsc_calc#225]
### Description of the bug

My input VCF specified through the sample_sheet.csv is not recognized (FileNotFound/ file doesn't exist from `pgscatalog_utils.samplesheet.check`) when the tool is launched from some directories, but IS recognized when the tool launched from other directories. I discovered this by chance when attempting to debug the `FileNotFound` I encountered on my first attempt at running the tool, I just so happened to launch it from a different directory without having changed anything else.

To be clear, `launchDir` and `workDir` change, but the `input` dir where sample sheet is stored and path to VCF do NOT change.

I have read and write permissions in all of these directories:
```
# successful dir
drwxr-sr-x. 18 nzeltser boutrosuser 16384 Jul  7 13:59 BZPRGPT1

# unsuccessful dir
drwxr-sr-x.  5 nzeltser boutrosuser     16384 Dec 29 22:09 polygenic-risk

```

I suspect this is some sort of mounting issue related to my Azure HPC environment and the docker platform, but I unfortunately don't have the expertise to troubleshoot further. It is perhaps worth noting that pgsc_calc was stored by default under $HOME which is in a different mount in our HPC from where the data are stored and the tools is launched.

Note, in the successful launches the tool seems to complete all relevant workflows but also fails to exit cleanly with:
```
ERROR ~ Failed to invoke `workflow.onComplete` event handler

 -- Check script '<HOME>/.nextflow/assets/pgscatalog/pgsc_calc/./workflows/pgscalc.nf' at line: 397 or see '.nextflow.log' file for more details
Completed at: 29-Dec-2023 22:24:41
Duration    : 1m 51s
CPU hours   : (a few seconds)
Succeeded   : 10
```

I think this is a separate issue though.

### Command used and terminal output

```console
nextflow run pgscatalog/pgsc_calc \
    -profile $PROFILE \
    --input $SAMPLE_SHEET \
    --target_build $TARGET_BUILD \
    --outdir $OUTDIR \
    --tracedir $OUTDIR \
    --pgs_id $PGS_ID \
    --min_overlap 0.5 \
    --parallel false \
    --max_memory 14.GB \
    --email $EMAIL

## Unsuccessful terminal output: ##

N E X T F L O W  ~  version 23.04.2
Launching `https://github.com/pgscatalog/pgsc_calc` [serene_jang] DSL2 - revision: 83326a1e60 [main]

WARN: Found unexpected parameters:
* --ref_format_version: v0.1
* --ancestry_checksums: <HOME>/.nextflow/assets/pgscatalog/pgsc_calc/assets/ancestry/checksums.txt
- Ignore this warning: params.schema_ignore_params = "ref_format_version,ancestry_checksums" 



------------------------------------------------------
  pgscatalog/pgsc_calc v2.0.0-alpha.4
------------------------------------------------------
Core Nextflow options
  revision          : main
  runName           : serene_jang
  containerEngine   : docker
  launchDir         : <WORK>/BZPRGPT2/polygenic-risk
  workDir           : <WORK>/BZPRGPT2/polygenic-risk/work
  projectDir        : <HOME>/.nextflow/assets/pgscatalog/pgsc_calc
  userName          : nzeltser
  profile           : docker
  configFiles       : <HOME>/nextflow/assets/pgscatalog/pgsc_calc/nextflow.config

Input/output options
  input             : <WORK>/BZPRGPT2/polygenic-risk/BZPRGPT2_marked-dups_expaned-by-500_gpt1-enriched-off-target/pgsc_calc/input/BZPRGPT2_sample-sheet.csv
  pgs_id            : PGS000662,PGS000030
  genotypes_cache   : null
  outdir            : <WORK>/BZPRGPT2/polygenic-risk/BZPRGPT2_marked-dups_expaned-by-500_gpt1-enriched-off-target/pgsc_calc/output
  email             : nzeltser@mednet.ucla.edu

Reference options
  run_ancestry      : null
  ref_samplesheet   : <HOME>/.nextflow/assets/pgscatalog/pgsc_calc/assets/ancestry/reference.csv
  ld_grch37         :<HOME>/.nextflow/assets/pgscatalog/pgsc_calc/assets/ancestry/high-LD-regions-hg19-GRCh37.txt
  ld_grch38         : <HOME>/.nextflow/assets/pgscatalog/pgsc_calc/assets/ancestry/high-LD-regions-hg38-GRCh38.txt

Compatibility options
  target_build      : GRCh38

Matching options
  min_overlap       : 0.5

Max job request options
  max_cpus          : 2
  max_memory        : 14.GB

Generic options
  tracedir          : <WORK>/BZPRGPT2/polygenic-risk/BZPRGPT2_marked-dups_expaned-by-500_gpt1-enriched-off-target/pgsc_calc/output

Other parameters
  ancestry_checksums: <HOME>/.nextflow/assets/pgscatalog/pgsc_calc/assets/ancestry/checksums.txt

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use pgscatalog/pgsc_calc for your analysis please cite:

* The Polygenic Score Catalog
  https://doi.org/10.1038/s41588-021-00783-5

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/pgscatalog/pgsc_calc/blob/master/CITATIONS.md
------------------------------------------------------
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:DOWNLOAD_SCOREFILES -

[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:DOWNLOAD_SCOREFILES                -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON       -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:COMBINE_SCOREFILES     -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM  -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELPVAR -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_VCF         -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATCH_VARIANTS               -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATCH_COMBINE                -

[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:DOWNLOAD_SCOREFILES                -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON       -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:COMBINE_SCOREFILES     -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM  -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELPVAR -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_VCF         -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATCH_VARIANTS               -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATCH_COMBINE                -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:PLINK2_SCORE           -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:SCORE_AGGREGATE        -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:REPORT:SCORE_REPORT                -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:DUMPSOFTWAREVERSIONS               -
...
executor >  local (2)
[d0/ac67de] process > PGSCATALOG_PGSCALC:PGSCALC:DOWNLOAD_SCOREFILES ([pgs_id:PGS000662 PGS000030, pgp_id:, trait_efo:]) [100%] 1 of 1 ✔
[96/e0761c] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (BZPRGPT2_sample-sheet.csv)                [  0%] 0 of 1
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:COMBINE_SCOREFILES                                          [  0%] 0 of 1
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM                                       -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELPVAR                                      -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_VCF                                              -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATCH_VARIANTS                                                    -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATCH_COMBINE                                                     -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:PLINK2_SCORE                                                -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:SCORE_AGGREGATE                                             -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:REPORT:SCORE_REPORT                                                     -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:DUMPSOFTWAREVERSIONS                                                    -
ERROR ~ Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (BZPRGPT2_sample-sheet.csv)'

Caused by:
  Process `PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (BZPRGPT2_sample-sheet.csv)` terminated with an error exit status (1)

Command executed:

  samplesheet_to_json BZPRGPT2_sample-sheet.csv out.json
  
  cat <<-END_VERSIONS > versions.yml
  SAMPLESHEET_JSON:
      python: $(echo $(python --version 2>&1) | cut -f 2 -d ' ')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  pgscatalog_utils.samplesheet.check: 2023-12-30 06:09:25 CRITICAL <WORK>/BZPRGPT2/regenotype-gSNP/output/regenotype-gSNP-3.0.0/BZPRGPT2_marked-dups_expanded-by-500_gpt1-enriched-off-target_all-sites/GATK-4.4.0.0/output/regenotyped_merged_recalibrated_SNP_AND_INDEL_filtered-PASS-only.vcf.gz doesn't exist, please check samplesheet path_prefix and try again
  pgscatalog_utils.samplesheet.check: 2023-12-30 06:09:25 CRITICAL If you're 100% sure this file exists and you're confused by this error, please check https://pgsc-calc.readthedocs.io/en/latest/how-to/mount.html
  Traceback (most recent call last):
    File "/venv/bin/samplesheet_to_json", line 8, in <module>
      sys.exit(check_samplesheet())
    File "/venv/lib/python3.10/site-packages/pgscatalog_utils/samplesheet/check.py", line 361, in check_samplesheet
      df = _setup_paths(df)
    File "/venv/lib/python3.10/site-packages/pgscatalog_utils/samplesheet/check.py", line 175, in _setup_paths
      resolved_paths: list[str] = _resolve_paths(
    File "/venv/lib/python3.10/site-packages/pgscatalog_utils/samplesheet/check.py", line 258, in _resolve_paths
      raise FileNotFoundError
  FileNotFoundError

Work dir:
  <WORK>/BZPRGPT2/polygenic-risk/work/96/e0761c833ca437e6d8eb506eeba88c

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details

## Successful run in a parent directory ##

N E X T F L O W  ~  version 23.04.2
Launching `https://github.com/pgscatalog/pgsc_calc` [reverent_marconi] DSL2 - revision: 83326a1e60 [main]

WARN: Found unexpected parameters:
* --ref_format_version: v0.1
* --ancestry_checksums: <HOME>/.nextflow/assets/pgscatalog/pgsc_calc/assets/ancestry/checksums.txt
- Ignore this warning: params.schema_ignore_params = "ref_format_version,ancestry_checksums" 



------------------------------------------------------
  pgscatalog/pgsc_calc v2.0.0-alpha.4
------------------------------------------------------
Core Nextflow options
  revision          : main
  runName           : reverent_marconi
  containerEngine   : docker
  launchDir         : <WORK>
  workDir           : <WORK>/work
  projectDir        : <HOME>/.nextflow/assets/pgscatalog/pgsc_calc
  userName          : nzeltser
  profile           : docker
  configFiles       : <HOME>/.nextflow/assets/pgscatalog/pgsc_calc/nextflow.config

Input/output options
  input             : <WORK>/BZPRGPT2/polygenic-risk/BZPRGPT2_marked-dups_expaned-by-500_gpt1-enriched-off-target/pgsc_calc/input/BZPRGPT2_sample-sheet.csv
  pgs_id            : PGS000662,PGS000030
  genotypes_cache   : null
  outdir            : <WORK>/BZPRGPT2/polygenic-risk/BZPRGPT2_marked-dups_expaned-by-500_gpt1-enriched-off-target/pgsc_calc/output
  email             : nzeltser@mednet.ucla.edu

Reference options
  run_ancestry      : null
  ref_samplesheet   : <HOME>/.nextflow/assets/pgscatalog/pgsc_calc/assets/ancestry/reference.csv
  ld_grch37         : <HOME>/.nextflow/assets/pgscatalog/pgsc_calc/assets/ancestry/high-LD-regions-hg19-GRCh37.txt
  ld_grch38         : <HOME>/.nextflow/assets/pgscatalog/pgsc_calc/assets/ancestry/high-LD-regions-hg38-GRCh38.txt

Compatibility options
  target_build      : GRCh38

Matching options
  min_overlap       : 0.5

Max job request options
  max_cpus          : 2
  max_memory        : 14.GB

Generic options
  tracedir          : <WORK>/BZPRGPT2/polygenic-risk/BZPRGPT2_marked-dups_expaned-by-500_gpt1-enriched-off-target/pgsc_calc/output

Other parameters
  ancestry_checksums: <HOME>/.nextflow/assets/pgscatalog/pgsc_calc/assets/ancestry/checksums.txt

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use pgscatalog/pgsc_calc for your analysis please cite:

* The Polygenic Score Catalog
  https://doi.org/10.1038/s41588-021-00783-5

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/pgscatalog/pgsc_calc/blob/master/CITATIONS.md
------------------------------------------------------
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:... -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:... -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:... -

[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:... -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:... -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:... -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:... -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:... -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:... -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:... -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:... -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:... -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:... -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:... -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:... -

...

executor >  local (10)
[01/8deb3e] process > PGSCATALOG_PGSCALC:PGSCALC:... [100%] 1 of 1 ✔
[98/3f98bf] process > PGSCATALOG_PGSCALC:PGSCALC:... [100%] 1 of 1 ✔
[a0/b46df2] process > PGSCATALOG_PGSCALC:PGSCALC:... [100%] 1 of 1 ✔
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:... -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:... -
[d0/f44e1d] process > PGSCATALOG_PGSCALC:PGSCALC:... [100%] 1 of 1 ✔
[c1/1f84a4] process > PGSCATALOG_PGSCALC:PGSCALC:... [100%] 1 of 1 ✔
[9b/2c2776] process > PGSCATALOG_PGSCALC:PGSCALC:... [100%] 1 of 1 ✔
[e7/b10765] process > PGSCATALOG_PGSCALC:PGSCALC:... [100%] 1 of 1 ✔
[61/ef8025] process > PGSCATALOG_PGSCALC:PGSCALC:... [100%] 1 of 1 ✔
[cc/e6f574] process > PGSCATALOG_PGSCALC:PGSCALC:... [100%] 1 of 1 ✔
[1b/2819cd] process > PGSCATALOG_PGSCALC:PGSCALC:... [100%] 1 of 1 ✔
WARN: Access to undefined parameter `max_multiqc_email_size` -- Initialise it to a default value eg. `params.max_multiqc_email_size = some_value`
ERROR ~ Failed to invoke `workflow.onComplete` event handler

 -- Check script '<HOME>/.nextflow/assets/pgscatalog/pgsc_calc/./workflows/pgscalc.nf' at line: 397 or see '.nextflow.log' file for more details
Completed at: 29-Dec-2023 22:24:41
Duration    : 1m 51s
CPU hours   : (a few seconds)
Succeeded   : 10
```

### System information

- Nextflow version: 23.04.2
- Hardware: Azure HPC
- Executor: slurm; but I ran these interactively in a compute node
- Container engine: Docker
- OS: Linux
- pgsc_calc version: v2.0.0-alpha.4

**Comment by smlmbrt** [comment]
Hi @alkaZeltser, I'm not an expert with Azure but I wonder if any general answers for Nextflow x Azure might be in the their docs: https://www.nextflow.io/docs/latest/azure.html?

**Comment by nebfield** [comment]
I think the problem might be caused by the `--email` parameter.  Could you try removing it and rerunning? Thanks!

**Comment by alkaZeltser** [comment]
Hi folks, thank you for your comments. I've been poking around a bit more, and I'm pretty sure that the issue is a result of nextflow to docker mounting procedures. Nextflow will mount the working directory and the directories of any explicit inputs (as provided in the nextflow run command) but the path provided in the sample sheet is not explicitly mounted. It is only accessible if it happens to be in a directory that is encompassed by one of the explicit mounts. In some cases this is not difficult for me to accommodate, but I have encountered a case where my genomic data files are sitting too far away. I attempted a sym-link but unfortunately that didn't work. Do you have any tips for modifying nextflow configs to allow additional mounts?

**Comment by alkaZeltser** [comment]
> I think the successful run error might be caused by the `--email` parameter. Could you try removing it and rerunning?
You were right, removing the email worked to silence the `ERROR ~ Failed to invoke `workflow.onComplete` event handler` error

**Comment by nebfield** [comment]
> Hi folks, thank you for your comments. I've been poking around a bit more, and I'm pretty sure that the issue is a result of nextflow to docker mounting procedures. Nextflow will mount the working directory and the directories of any explicit inputs (as provided in the nextflow run command) but the path provided in the sample sheet is not explicitly mounted. It is only accessible if it happens to be in a directory that is encompassed by one of the explicit mounts. In some cases this is not difficult for me to accommodate, but I have encountered a case where my genomic data files are sitting too far away. I attempted a sym-link but unfortunately that didn't work. Do you have any tips for modifying nextflow configs to allow additional mounts?

Adapting [this singularity example might be helpful](https://pgsc-calc.readthedocs.io/en/latest/how-to/mount.html)

```
docker {
  enabled = true
  runOptions = '-v /path/to/genomes:/path/to/genomes'
}
```

**Comment by alkaZeltser** [comment]
> Adapting [this singularity example might work](https://pgsc-calc.readthedocs.io/en/latest/how-to/mount.html)
> 
> ```
> docker {
>   enabled = true
>   runOptions = '-v /path/to/genomes:/path/to/genomes'
> }
> ```
> 
> This should mount the directory from your host filesystem to the same place inside the docker container.

I've found a solution that works well, but with a necessary modification to the suggestion, so I felt it was worth documenting some details in case it is useful to anyone else.


To recap the problem:
1. Paths to input filesets provided in the sample sheet are not mounted to docker in a process-specific scope in the process that checks if these files are valid: `PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON`
2. If the input files are stored outside of directories that are automatically mounted globally, e.g. `workDir` `launchDir` `outdir`, then `SAMPLESHEET_JSON` will not have access to them and will throw a `FileNotFound` error.

Suggested solution: add input fileset path to global docker `runOptions` so that it is mounted before any processes are launched. Adding the following code to an external config file achieved this. The config file was passed to the nextflow command using `nextflow run pgscatalog/pgsc_calc -c $EXTRA_CONFIG --mount $MOUNTDIR`

Contents of `$EXTRA_CONFIG`:

```
profiles {
    docker {
        def platform = params.platform == 'arm64' ? '--platform linux/arm64' : '--platform linux/amd64'
        def extra_mount = "-v $params.mount:$params.mount"
        docker.runOptions      = [extra_mount, '-u $(id -u):$(id -g) ', platform].join(' ')
        docker.enabled         = true
        docker.userEmulation   = true
        singularity.enabled    = false
        podman.enabled         = false
        shifter.enabled        = false
        charliecloud.enabled   = false
    }
}
```

While this satisfies `SAMPLESHEET_JSON`, this method results in an error in the subsequent process, the very first plink process: `PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELPVAR`

```
error [nextflow.exception.ProcessFailedException]: Process `PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELPVAR ` terminated with an error exit status (125)
docker: Error response from daemon: Duplicate mount point: [/path/to/$MOUNTDIR]
```
The error is a `Duplicate mount point` error from docker, because here is where the input filesets are actually mounted for the first time. They are extracted from the sample sheet by the input checker [here](https://github.com/PGScatalog/pgsc_calc/blob/83326a1e6030d6dff2e0e1ac71a0e0caf446e2f4/subworkflows/local/input_check.nf#L29C5-L40C14) and passed to plink through `MAKE_COMPATIBLE` [here](https://github.com/PGScatalog/pgsc_calc/blob/83326a1e6030d6dff2e0e1ac71a0e0caf446e2f4/workflows/pgscalc.nf#L245C2-L252C10) at which point nextflow attempts to properly mount them for the first time to docker, except it's not the first time, since I've already mounted their directory globally through my extra config file. Thus, a duplicate mount point.

Here's the final solution we settled on:
Instead of mounting the extra directory globally, we instead mount it in a process-specific scope with the following configuration of `containerOptions`:

```
process {

    withName: SAMPLESHEET_JSON {
        containerOptions = {-> "-v ${params.mount}:${params.mount}" }
        }
}
```

This worked, and I was able to complete a full run of pgsc_calc. 

>A quick aside: when this tool works, it works super well. It calculated two scores in a full imputation file (from TopMed) containing tens of thousands of samples in 40 minutes. I had to tweak some of the memory allocations to work with our HPC, but once all processes had sufficient memory there were no further issues.

I think the main issue here is still the fact that `SAMPLESHEET_JSON` does not mount the very inputs it is checking. This seems odd, but at least there is a simple workaround.

**Comment by nebfield** [comment]
Thanks for documenting your fix 😄 I'm glad it's working for you.

> I think the main issue here is still the fact that `SAMPLESHEET_JSON` does not mount the very inputs it is checking. This seems odd, but at least there is a simple workaround.

That's an interesting idea I hadn't thought of. Nextflow is responsible for configuring and orchestrating the containers, so the CLI applications aren't able to edit the containers they're running inside. 

I'll investigate and see if I can figure out a workaround https://github.com/PGScatalog/pgsc_calc/issues/240
