### ISSUE TITLE
pgsc_calc making files in root for unknown reason (Singularity) ("cp: cannot stat '/root/.nextflow ... No such file or directory")

### ISSUE THREAD

**Issue by Fiwx** [PGScatalog/pgsc_calc#248]
### Description of the bug

I am in a user account, ubuntu.

I installed Singularity and its dependencies on the user ubuntu, not root.

I used root to install nextflow as I was having trouble installing on ubuntu. I wrote a script to transfer ownership of all root files involving nextflow to ownership by ubuntu. I then verified that every nextflow-related file is owned by ubuntu.

Then, I run this:
```sudo nextflow run pgscatalog/pgsc_calc -profile test,singularity```

The result is ```  cp: cannot stat '/root/.nextflow/assets/pgscatalog/pgsc_calc/assets/report/*': No such file or directory```

Without -profile, it will output this:
```
Command executed:

 echo nextflow run /home/ubuntu/dir/tools/pgsc_calc/main.nf -profile singularity --input /home/ubuntu/dir/run/test/samplesheet.csv --pgs_id PGS003724 --target_build GRCh37 --min_overlap 0.0 -c /home/ubuntu/dir/references/custom.config > command.txt
  echo "keep_multiallelic: false" > params.txt
  echo "keep_ambiguous   : false"    >> params.txt
  echo "min_overlap      : 0.0"       >> params.txt
  
  cp -r /home/ubuntu/dir/tools/pgsc_calc/assets/report/* .
  # workaround for unhelpful filenotfound quarto errors in some HPCs
  mkdir temp && TMPDIR=temp
  
  quarto render report.qmd -M "self-contained:true"         -P score_path:aggregated_scores.txt.gz         -P sampleset:test         -P run_ancestry:false         -P reference_panel_name:NO_PANEL
  
  cat <<-END_VERSIONS > versions.yml
  SCORE_REPORT:
      R: $(echo $(R --version 2>&1) | head -n 1 | cut -f 3 -d ' ')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
  error: Could not create TypeScript compiler cache location: "/root/.cache/deno/gen"
```

### Command used and terminal output

```console
Command:
 nextflow run pgscatalog/pgsc_calc -profile test,singularity


Output:
```  cp: cannot stat '/root/.nextflow/assets/pgscatalog/pgsc_calc/assets/report/*': No such file or directory```
```

### Relevant files

Command executed:

  echo nextflow run pgscatalog/pgsc_calc -profile test,singularity > command.txt
  echo "keep_multiallelic: false" > params.txt
  echo "keep_ambiguous   : false"    >> params.txt
  echo "min_overlap      : 0.75"       >> params.txt
  
  cp -r /root/.nextflow/assets/pgscatalog/pgsc_calc/assets/report/* .
  # workaround for unhelpful filenotfound quarto errors in some HPCs
  mkdir temp && TMPDIR=temp
  
  quarto render report.qmd -M "self-contained:true"         -P score_path:aggregated_scores.txt.gz         -P sampleset:cineca         -P run_ancestry:false         -P reference_panel_name:NO_PANEL
  
  cat <<-END_VERSIONS > versions.yml
  SCORE_REPORT:
      R: $(echo $(R --version 2>&1) | head -n 1 | cut -f 3 -d ' ')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

### System information

System Summary

Hardware:
CPU: Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz
Operating System: Ubuntu; Version: 22.04.3 LTS (Jammy Jellyfish)
Executor: None configured in the current directory (Nextflow defaults to local executor)
Docker: Version 25.0.3, build 4debf41
Singularity: Version 3.8.7
Nextflow: Version 23.10.1 build 5891

**Comment by nebfield** [comment]
When you run a nextflow workflow using:`$ nextflow run pgscatalog/pgsc_calc` `it installs the repository to `$NXF_HOME/<organisation>/<repo>/assets` So in your case because you installed nextflow as root the workflow isn't making files in `/root/.nextflow`, it's trying to copy them from the installation directory.

You can fix this by doing one of:

* Installing nextflow on the ubuntu user only (never using the root account) 
* deleting `/root/.nextflow`, and [setting `$NXF_HOME` to something](https://www.nextflow.io/docs/latest/config.html#environment-variables) like `/home/ubuntu/.nextflow`
* cloning the repository manully and running the workflow directly as the ubuntu user

```
$ git clone https://github.com/PGScatalog/pgsc_calc.git
$ cd pgsc_calc
$ nextflow run main.nf -profile singularity ...
```

**Comment by Fiwx** [comment]
@nebfield Thanks! This worked pretty well. Now, the test run works well and runs to successful completion.

For future users, this was my experience (you may have different results): 
- Installing nextflow on the ubuntu user only (never using the root account) ✅ this worked! I also called nextflow directly (without adding it to path).
- deleting /root/.nextflow, and setting $NXF_HOME to something like /home/ubuntu/.nextflow ❌ this did not work for me
- setting $NXF_ASSETS ❌ this did not work for me, in the way that I did it
- cloning the repository manually and running the workflow directly as the ubuntu user ❌ though the error is different, it still tries to use root

However, running it on an actual file (no test profile) results in this:
```
  error: Could not create TypeScript compiler cache location: "/home/ubuntu/.cache/deno/gen"
  Check the permission of the directory.
```

I made /home/ubuntu/.cache/deno/gen beforehand and changed the permissions to be wide open. Upon failure, I checked the permissions again:
```Permissions of /home/ubuntu/.cache/deno/gen: drwxrwxrwt```

Ideas:

- Modify the nextflow .config file?
- Set permissions some other way?
- Testing using mkdir -p $HOME/.cache/deno/gen (though $HOME is just /home/ubuntu so it shouldn't be different)

**Comment by Fiwx** [comment]
Additional information:


```
[ae/5175fd] process > PGSCATALOG_PGSCALC:PGSCALC:DOWNLOAD_SCOREFILES ([pgs_id:PGS003724, pgp_id:, trait_efo:]) [100%] 1 of 1 ✔
executor >  local (3)
[ae/5175fd] process > PGSCATALOG_PGSCALC:PGSCALC:DOWNLOAD_SCOREFILES ([pgs_id:PGS003724, pgp_id:, trait_efo:]) [100%] 1 of 1 ✔
executor >  local (8)
[ae/5175fd] process > PGSCATALOG_PGSCALC:PGSCALC:DOWNLOAD_SCOREFILES ([pgs_id:PGS003724, pgp_id:, trait_efo:])         [100%] 1 of 1 ✔
executor >  local (8)
[ae/5175fd] process > PGSCATALOG_PGSCALC:PGSCALC:DOWNLOAD_SCOREFILES ([pgs_id:PGS003724, pgp_id:, trait_efo:])         [100%] 1 of 1 ✔
executor >  local (9)
[ae/5175fd] process > PGSCATALOG_PGSCALC:PGSCALC:DOWNLOAD_SCOREFILES ([pgs_id:PGS003724, pgp_id:, trait_efo:])         [100%] 1 of 1 ✔
executor >  local (9)
[ae/5175fd] process > PGSCATALOG_PGSCALC:PGSCALC:DOWNLOAD_SCOREFILES ([pgs_id:PGS003724, pgp_id:, trait_efo:])         [100%] 1 of 1 ✔
executor >  local (10)
[ae/5175fd] process > PGSCATALOG_PGSCALC:PGSCALC:DOWNLOAD_SCOREFILES ([pgs_id:PGS003724, pgp_id:, trait_efo:])         [100%] 1 of 1 ✔
executor >  local (10)
[ae/5175fd] process > PGSCATALOG_PGSCALC:PGSCALC:DOWNLOAD_SCOREFILES ([pgs_id:PGS003724, pgp_id:, trait_efo:])         [100%] 1 of 1 ✔
[f1/868c88] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)                        [100%] 1 of 1 ✔
[4b/6dcd69] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:COMBINE_SCOREFILES (1)                                    [100%] 1 of 1 ✔
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM                                     -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELPVAR                                    -
[74/bf2a6b] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_VCF (test chromosome ALL)                      [100%] 1 of 1 ✔
[d2/ac3728] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATCH_VARIANTS (test chromosome ALL)                            [100%] 1 of 1 ✔
[3a/f0a89e] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATCH_COMBINE (test)                                            [100%] 1 of 1 ✔
[63/8d1fa9] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:PLINK2_SCORE (test chromosome ALL effect type additive 0) [100%] 1 of 1 ✔
[38/65371f] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:SCORE_AGGREGATE (test)                                    [100%] 1 of 1 ✔
[ae/7d0253] process > PGSCATALOG_PGSCALC:PGSCALC:REPORT:SCORE_REPORT (test)                                            [  0%] 0 of 1 ✔
[17/9e3713] process > PGSCATALOG_PGSCALC:PGSCALC:DUMPSOFTWAREVERSIONS (1)                                              [100%] 1 of 1 ✔
ERROR ~ Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:REPORT:SCORE_REPORT (test)'

Caused by:
  Process `PGSCATALOG_PGSCALC:PGSCALC:REPORT:SCORE_REPORT (test)` terminated with an error exit status (1)

Command executed:

  echo nextflow run /home/ubuntu/dir/tools/pgsc_calc/main.nf -profile singularity --input /home/ubuntu/dir/run/test/samplesheet.csv --pgs_id PGS003724 --target_build GRCh37 --min_overlap 0.0 -c /home/ubuntu/dir/references/custom.config > command.txt
  echo "keep_multiallelic: false" > params.txt
  echo "keep_ambiguous   : false"    >> params.txt
  echo "min_overlap      : 0.0"       >> params.txt
  
  cp -r /home/ubuntu/dir/tools/pgsc_calc/assets/report/* .
  # workaround for unhelpful filenotfound quarto errors in some HPCs
  mkdir temp && TMPDIR=temp
  
  quarto render report.qmd -M "self-contained:true"         -P score_path:aggregated_scores.txt.gz         -P sampleset:test         -P run_ancestry:false         -P reference_panel_name:NO_PANEL
  
  cat <<-END_VERSIONS > versions.yml
  SCORE_REPORT:
      R: $(echo $(R --version 2>&1) | head -n 1 | cut -f 3 -d ' ')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
  error: Could not create TypeScript compiler cache location: "/home/ubuntu/.cache/deno/gen"
  Check the permission of the directory.

```

**Comment by nebfield** [comment]
I found some issues with the report container configuration which can sometimes cause these kinds of problems 

We'll do a new release `a2.5` at the end of next week-ish which may help 😄

**Comment by Fiwx** [comment]
I tested this in a different setup and was able to replicate the  error```Command error:
  error: Could not create TypeScript compiler cache location: "/home/ubuntu/.cache/deno/gen"``` (``` quarto render report.qmd -M "self-contained:true"         -P score_path:aggregated_scores.txt.gz         -P sampleset:test         -P run_ancestry:false         -P reference_panel_name:NO_PANEL```).

Same as before, the test profile worked but the full run failed.

I confirmed it is not due to the directory's existence or ownership.

Next, I ran pgsc_calc but used Docker instead of Singularity to determine if the error is related to Singularity. The same command ran with Docker executed perfectly without the .cache/deno/gen location, so it must be something related to Singularity.

**Comment by nebfield** [comment]
Could you test again with the latest release please? Sorry it was a little late!

**Comment by samreenzafer** [comment]
> I tested this in a different setup and was able to replicate the error`Command error: error: Could not create TypeScript compiler cache location: "/home/ubuntu/.cache/deno/gen"` (` quarto render report.qmd -M "self-contained:true" -P score_path:aggregated_scores.txt.gz -P sampleset:test -P run_ancestry:false -P reference_panel_name:NO_PANEL`).
> 
> Same as before, the test profile worked but the full run failed.
> 
> I confirmed it is not due to the directory's existence or ownership.
> 
> Next, I ran pgsc_calc but used Docker instead of Singularity to determine if the error is related to Singularity. The same command ran with Docker executed perfectly without the .cache/deno/gen location, so it must be something related to Singularity.

Hi 
Did you ever try to run this with singularity again to see if the error regarding " .cache/deno/gen " vanished or not? I'm using the latest singularity and nextflow versions on our department HPC cluster and getting the same error at the  'SCORE_REPORT' module of the workflow. 

```

export NXF_SINGULARITY_CACHEDIR="/sc/arion/projects/PRS/pgsc-calc/work/singularity/"
nextflow run pgscatalog/pgsc_calc --max_cpus 1 -profile singularity --input biome_cnics_plink/samplesheet.BiomeCNICS.csv --pgs_id PGS003446,PGS002237 --target_build GRCh37 -w /hpc/users/zafers02/HIV_SamreenPaola/PRS/test_nextflow_1/work/  --genotypes_cache /sc/arion/projects/PRS/test_nextflow_1/genotypes_cache --min_overlap 0.20 --run_ancestry /sc/arion/projects/PRS/pgsc-calc/resources/pgsc_HGDP+1kGP_v1.tar.zst  -resume -latest 

 N E X T F L O W   ~  version 24.04.2

Pulling pgscatalog/pgsc_calc ...
 Already-up-to-date
Launching `https://github.com/pgscatalog/pgsc_calc` [agitated_wiles] DSL2 - revision: ccfd6367d5 [main]

------------------------------------------------------
  pgscatalog/pgsc_calc v2.0.0-beta-gccfd636
------------------------------------------------------

[dd/496c4b] process > PGSCATALOG_PGSCCALC:PGSCCALC:DOWNLOAD_SCOREFILES ([pgs_id:PGS003446 PGS002237, pgp_id:, trait_efo:])    [100%] 1 of 1 ✔
[86/c7ad10] process > PGSCATALOG_PGSCCALC:PGSCCALC:INPUT_CHECK:COMBINE_SCOREFILES (1)                                         [100%] 1 of 1 ✔
[skipped  ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM (BiomeCnics chromosome ALL)              [100%] 1 of 1, stored: 1 ✔
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELPVAR                                         -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_VCF                                                 -
[skipped  ] process > PGSCATALOG_PGSCCALC:PGSCCALC:ANCESTRY_PROJECT:EXTRACT_DATABASE (1)                                      [100%] 1 of 1, stored: 1 ✔
executor >  local (21)
[dd/496c4b] process > PGSCATALOG_PGSCCALC:PGSCCALC:DOWNLOAD_SCOREFILES ([pgs_id:PGS003446 PGS002237, pgp_id:, trait_efo:])    [100%] 1 of 1 ✔
[86/c7ad10] process > PGSCATALOG_PGSCCALC:PGSCCALC:INPUT_CHECK:COMBINE_SCOREFILES (1)                                         [100%] 1 of 1 ✔
[skipped  ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM (BiomeCnics chromosome ALL)              [100%] 1 of 1, stored: 1 ✔
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_RELABELPVAR                                         -
[-        ] process > PGSCATALOG_PGSCCALC:PGSCCALC:MAKE_COMPATIBLE:PLINK2_VCF                                                 -
[skipped  ] process > PGSCATALOG_PGSCCALC:PGSCCALC:ANCESTRY_PROJECT:EXTRACT_DATABASE (1)                                      [100%] 1 of 1, stored: 1 ✔
[6e/3b81af] process > PGSCATALOG_PGSCCALC:PGSCCALC:ANCESTRY_PROJECT:INTERSECT_VARIANTS (BiomeCnics chromosome ALL)            [100%] 1 of 1 ✔
[e8/a8fde7] process > PGSCATALOG_PGSCCALC:PGSCCALC:ANCESTRY_PROJECT:FILTER_VARIANTS (BiomeCnics GRCh37)                       [100%] 1 of 1 ✔
[59/188612] process > PGSCATALOG_PGSCCALC:PGSCCALC:ANCESTRY_PROJECT:PLINK2_MAKEBED_REF (reference)                            [100%] 1 of 1 ✔
[c9/3e550c] process > PGSCATALOG_PGSCCALC:PGSCCALC:ANCESTRY_PROJECT:INTERSECT_THINNED (BiomeCnics)                            [100%] 1 of 1 ✔
[da/ad229e] process > PGSCATALOG_PGSCCALC:PGSCCALC:ANCESTRY_PROJECT:RELABEL_IDS (BiomeCnics null pvar)                        [100%] 1 of 1 ✔
[02/04baf1] process > PGSCATALOG_PGSCCALC:PGSCCALC:ANCESTRY_PROJECT:PLINK2_MAKEBED_TARGET (BiomeCnics)                        [100%] 1 of 1 ✔
[55/d7b7f1] process > PGSCATALOG_PGSCCALC:PGSCCALC:ANCESTRY_PROJECT:PLINK2_ORIENT (BiomeCnics)                                [100%] 1 of 1 ✔
[ab/ccfa15] process > PGSCATALOG_PGSCCALC:PGSCCALC:ANCESTRY_PROJECT:FRAPOSA_PCA (reference)                                   [100%] 1 of 1 ✔
[7a/8d43dd] process > PGSCATALOG_PGSCCALC:PGSCCALC:ANCESTRY_PROJECT:FRAPOSA_PROJECT (BiomeCnics)                              [100%] 1 of 1 ✔
[2c/f17610] process > PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_VARIANTS (BiomeCnics chromosome ALL)                           [100%] 1 of 1 ✔
[5c/4b4538] process > PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_COMBINE (BiomeCnics)                                           [100%] 1 of 1 ✔
[06/03fcf7] process > PGSCATALOG_PGSCCALC:PGSCCALC:APPLY_SCORE:RELABEL_SCOREFILES (BiomeCnics additive scorefile)             [100%] 1 of 1 ✔
[df/399166] process > PGSCATALOG_PGSCCALC:PGSCCALC:APPLY_SCORE:RELABEL_AFREQ (BiomeCnics null afreq)                          [100%] 1 of 1 ✔
[68/ff1f63] process > PGSCATALOG_PGSCCALC:PGSCCALC:APPLY_SCORE:PLINK2_SCORE (reference chromosome ALL effect type additive 0) [100%] 2 of 2 ✔
[cf/ed0399] process > PGSCATALOG_PGSCCALC:PGSCCALC:APPLY_SCORE:SCORE_AGGREGATE (BiomeCnics)                                   [100%] 1 of 1 ✔
[1e/4f46f1] process > PGSCATALOG_PGSCCALC:PGSCCALC:REPORT:ANCESTRY_ANALYSIS (1)                                               [100%] 1 of 1 ✔
[b2/e0aea2] process > PGSCATALOG_PGSCCALC:PGSCCALC:REPORT:SCORE_REPORT (BiomeCnics)                                           [100%] 1 of 1, failed: 1 ✘
[58/3b133d] process > PGSCATALOG_PGSCCALC:PGSCCALC:DUMPSOFTWAREVERSIONS (1)                                                   [100%] 1 of 1 ✔
Execution cancelled -- Finishing pending tasks before exit
ERROR ~ Error executing process > 'PGSCATALOG_PGSCCALC:PGSCCALC:REPORT:SCORE_REPORT (BiomeCnics)'

Caused by:
  Process `PGSCATALOG_PGSCCALC:PGSCCALC:REPORT:SCORE_REPORT (BiomeCnics)` terminated with an error exit status (1)

Command executed:

  export TMPDIR=$PWD # tmpdir must always be writable for quarto
  echo nextflow run pgscatalog/pgsc_calc --max_cpus 1 -profile singularity --input biome_cnics_plink/samplesheet.BiomeCNICS.csv --pgs_id PGS003446,PGS002237 --target_build GRCh37 -w /hpc/users/zafers02/HIV_SamreenPaola/PRS/test_nextflow_1/work/ --genotypes_cache /sc/arion/projects/PRS/test_nextflow_1/genotypes_cache --min_overlap 0.20 --run_ancestry /sc/arion/projects/PRS/pgsc-calc/resources/pgsc_HGDP+1kGP_v1.tar.zst -resume -latest > command.txt
  
  echo "keep_multiallelic: false" > params.txt
  echo "keep_ambiguous   : false"    >> params.txt
  echo "min_overlap      : 0.2"       >> params.txt
  
  quarto render report.qmd -M "self-contained:true"         -P score_path:BiomeCnics_pgs.txt.gz         -P sampleset:BiomeCnics         -P run_ancestry:true         -P reference_panel_name:HGDP+1kGP         -P version:2.0.0-beta         -o report.html
  
  cat <<-END_VERSIONS > versions.yml
  SCORE_REPORT:
      R: $(echo $(R --version 2>&1) | head -n 1 | cut -f 3 -d ' ')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  error: Uncaught PermissionDenied: Permission denied (os error 13): mkdir '/tmp/quarto_cache_home/quarto'
          Deno.mkdirSync(dir, {
               ^
      at Object.mkdirSync (ext:deno_fs/30_fs.js:132:7)
      at ensureDirSync (file:///opt/quarto/bin/quarto.js:9288:14)
      at quartoDir (file:///opt/quarto/bin/quarto.js:33006:5)
      at quartoCacheDir (file:///opt/quarto/bin/quarto.js:32998:12)
      at file:///opt/quarto/bin/quarto.js:39501:25

Work dir:
  /hpc/users/zafers02/HIV_SamreenPaola/PRS/test_nextflow_1/work/b2/e0aea27e406e462a2f023c2720b3ba

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
ERROR ~ ERROR: No results report written!

 -- Check '.nextflow.log' file for details


```

**Comment by Fiwx** [comment]
I got the "no loop devices available" error on the most recent version. Inspecting the devices, I see:

```
/dev/loop6: [0042]:993528 (/source/user/singularity_containers/ghcr.io-pgscatalog-pygscatalog-pgscatalog-utils-1.3.1-singularity.img), offset 40960, sizelimit 553119744
```

Could this mean there is a limit of 553 MB on the loop device, and this is exceeded when too many scorefiles are used at once?

**Comment by Fiwx** [comment]
Running bash .command.run does not result in an error. It runs through correctly.
