### ISSUE TITLE
Issue on v2.0.0-beta.2 when running many scorefiles: run_match FileExistsError with pgscatalog-match step

### ISSUE THREAD

**Issue by Fiwx** [PGScatalog/pgsc_calc#357]
### Description of the bug

v2.0.0-beta.2 succeeded with a bit over a dozen scores, but I increased the number of scores to around 50, and got the error:
```Aug-07 08:07:48.595 [TaskFinalizer-6] ERROR nextflow.processor.TaskProcessor - Error executing process > 'PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_VARIANTS (sample1228 chromosome ALL)'```

Running .command.run results in a FileExistsError, but also deletes the offending file, so that when I run it again, it does not have a FileExistsError on the same error. 

### Command used and terminal output

```console
[...]

> TaskHandler[id: 7; name: PGSCATALOG_PGSCCALC:PGSCCALC:ANCESTRY_PROJECT:FILTER_VARIANTS (sample1228 GRCh37); status: NEW; exit: -; error: -; workDir: /home/ubuntu/user/rundir/test/sample_1228/work/c2/ed1dcfef9f113168c6b82e44cd1bd2]
Aug-07 08:07:48.532 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 6; name: PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_VARIANTS (sample1228 chromosome ALL); status: COMPLETED; exit: 137; error: -; workDir: /home/ubuntu/user/rundir/test/sample_1228/work/5d/058b620cca1d372ae4d78f7cddea16]
Aug-07 08:07:48.551 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Aug-07 08:07:48.553 [Task submitter] INFO  nextflow.Session - [c2/ed1dcf] Submitted process > PGSCATALOG_PGSCCALC:PGSCCALC:ANCESTRY_PROJECT:FILTER_VARIANTS (sample1228 GRCh37)
Aug-07 08:07:48.555 [TaskFinalizer-6] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_VARIANTS (sample1228 chromosome ALL); work-dir=/home/ubuntu/user/rundir/test/sample_1228/work/5d/058b620cca1d372ae4d78f7cddea16
  error [nextflow.exception.ProcessFailedException]: Process `PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_VARIANTS (sample1228 chromosome ALL)` terminated with an error exit status (137)
Aug-07 08:07:48.595 [TaskFinalizer-6] ERROR nextflow.processor.TaskProcessor - Error executing process > 'PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_VARIANTS (sample1228 chromosome ALL)'

Caused by:
  Process `PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_VARIANTS (sample1228 chromosome ALL)` terminated with an error exit status (137)


Command executed:

  export POLARS_MAX_THREADS=2

  pgscatalog-match                  --dataset sample1228         --scorefile scorefiles.txt.gz         --target GRCh37_sample1228_ALL.pvar.zst         --only_match                                    --outdir $PWD         -v

  cat <<-END_VERSIONS > versions.yml
  MATCH_VARIANTS:
      pgscatalog.match: $(echo $(python -c 'import pgscatalog.match; print(pgscatalog.match.__version__)'))
  END_VERSIONS

Command exit status:
  137

Command output:
  (empty)

Command error:
  pgscatalog.match.cli.match_cli: 2024-08-07 07:57:40 WARNING  No output format specified, writing to combined scoring file
  pgscatalog.match.cli.match_cli: 2024-08-07 07:57:40 DEBUG    Verbose logging enabled
  pgscatalog.match.cli.match_cli: 2024-08-07 07:57:40 INFO     --cleanup set (default), temporary files will be deleted
  pgscatalog.match.lib.scoringfileframe: 2024-08-07 07:57:40 DEBUG    Converting ScoringFileFrame(NormalisedScoringFile('scorefiles.txt.gz')) to feather format
  pgscatalog.match.lib.scoringfileframe: 2024-08-07 07:58:14 DEBUG    ScoringFileFrame(NormalisedScoringFile('scorefiles.txt.gz')) feather conversion complete
  pgscatalog.match.lib._match.preprocess: 2024-08-07 07:58:14 DEBUG    Complementing column effect_allele
  pgscatalog.match.lib._match.preprocess: 2024-08-07 07:58:14 DEBUG    Complementing column other_allele
  pgscatalog.match.lib.variantframe: 2024-08-07 07:58:14 DEBUG    Converting VariantFrame(path='GRCh37_sample1228_ALL.pvar.zst', dataset='sample1228', chrom=None, cleanup=True, tmpdir=PosixPath('tmp')) to feather format
  pgscatalog.match.lib.variantframe: 2024-08-07 07:58:30 DEBUG    VariantFrame(path='GRCh37_sample1228_ALL.pvar.zst', dataset='sample1228', chrom=None, cleanup=True, tmpdir=PosixPath('tmp')) feather conversion complete
  pgscatalog.match.lib._match.preprocess: 2024-08-07 07:58:30 DEBUG    Filtering target to include chromosomes 1 - 22, X, Y
  pgscatalog.match.lib._match.preprocess: 2024-08-07 07:58:33 DEBUG    No multiallelic variants detected
  pgscatalog.match.lib._match.match: 2024-08-07 07:58:33 DEBUG    Getting matches for scores with effect allele and other allele
  pgscatalog.match.lib._match.match: 2024-08-07 07:58:33 DEBUG    Matching strategy: refalt
  pgscatalog.match.lib._match.match: 2024-08-07 07:58:33 DEBUG    Matching strategy: altref
  pgscatalog.match.lib._match.match: 2024-08-07 07:58:33 DEBUG    Matching strategy: refalt_flip
  pgscatalog.match.lib._match.match: 2024-08-07 07:58:33 DEBUG    Matching strategy: altref_flip
  pgscatalog.match.lib._match.match: 2024-08-07 07:58:33 DEBUG    Getting matches for scores with effect allele only
  pgscatalog.match.lib._match.match: 2024-08-07 07:58:33 DEBUG    Matching strategy: no_oa_ref
  pgscatalog.match.lib._match.match: 2024-08-07 07:58:33 DEBUG    Matching strategy: no_oa_alt
  pgscatalog.match.lib._match.match: 2024-08-07 07:58:33 DEBUG    Matching strategy: no_oa_ref_flip
  pgscatalog.match.lib._match.match: 2024-08-07 07:58:33 DEBUG    Matching strategy: no_oa_alt_flip
  .command.sh: line 4:    37 Killed                  pgscatalog-match --dataset sample1228 --scorefile scorefiles.txt.gz --target GRCh37_sample1228_ALL.pvar.zst --only_match --outdir $PWD -v

Work dir:
  /home/ubuntu/user/rundir/test/sample_1228/work/5d/058b620cca1d372ae4d78f7cddea16

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
Aug-07 08:07:48.609 [TaskFinalizer-6] INFO  nextflow.Session - Execution cancelled -- Finishing pending tasks before exit
Aug-07 08:07:48.617 [Actor Thread 81] ERROR nextflow.Nextflow - ERROR: Matching subworkflow failed
Aug-07 08:07:48.645 [main] DEBUG nextflow.Session - Session await > all processes finished
Aug-07 08:07:48.678 [Actor Thread 96] ERROR nextflow.Nextflow - ERROR: No scores calculated!
Aug-07 08:07:48.678 [Actor Thread 99] ERROR nextflow.Nextflow - ERROR: Projection subworkflow failed
Aug-07 08:07:48.686 [Actor Thread 94] ERROR nextflow.Nextflow - ERROR: No results report written!


[bash .command.run results below. Before running, matchtmp is present.]

pgscatalog.match.cli.match_cli: 2024-08-07 10:42:07 WARNING  No output format specified, writing to combined scoring file
pgscatalog.match.cli.match_cli: 2024-08-07 10:42:07 DEBUG    Verbose logging enabled
pgscatalog.match.cli.match_cli: 2024-08-07 10:42:07 INFO     --cleanup set (default), temporary files will be deleted
Traceback (most recent call last):  File "/app/pgscatalog.utils/.venv/bin/pgscatalog-match", line 8, in <module>
    sys.exit(run_match())
             ^^^^^^^^^^^
  File "/app/pgscatalog.utils/.venv/lib/python3.11/site-packages/pgscatalog/match/cli/match_cli.py", line 60, in run_match
    Config.MATCHTMP.mkdir(exist_ok=False)
  File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/home/ubuntu/user/rundir/test/sample_1228/work/5d/058b620cca1d372ae4d78f7cddea16/matchtmp'



[running .command.run again now that matchtmp is gone. tmp is present.]


pgscatalog.match.cli.match_cli: 2024-08-07 10:45:48 WARNING  No output format specified, writing to combined scoring filepgscatalog.match.cli.match_cli: 2024-08-07 10:45:48 DEBUG    Verbose logging enabledpgscatalog.match.cli.match_cli: 2024-08-07 10:45:48 INFO     --cleanup set (default), temporary files will be deletedTraceback (most recent call last):
  File "/app/pgscatalog.utils/.venv/bin/pgscatalog-match", line 8, in <module>    sys.exit(run_match())             ^^^^^^^^^^^  File "/app/pgscatalog.utils/.venv/lib/python3.11/site-packages/pgscatalog/match/cli/match_cli.py", line 62, in run_match
    Config.TMPDIR.mkdir(exist_ok=False)  File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/home/ubuntu/user/rundir/test/sample_1228/work/5d/058b620cca1d372ae4d78f7cddea16/tmp'

[.command.run a third time. tmp is not present]


pgscatalog.match.cli.match_cli: 2024-08-07 10:46:11 WARNING  No output format specified, writing to combined scoring file
pgscatalog.match.cli.match_cli: 2024-08-07 10:46:11 DEBUG    Verbose logging enabled
pgscatalog.match.cli.match_cli: 2024-08-07 10:46:11 INFO     --cleanup set (default), temporary files will be deletedpgscatalog.match.lib.scoringfileframe: 2024-08-07 10:46:11 DEBUG    Converting ScoringFileFrame(NormalisedScoringFile('scorefiles.txt.gz')) to feather formatpgscatalog.match.lib.scoringfileframe: 2024-08-07 10:46:45 DEBUG    ScoringFileFrame(NormalisedScoringFile('scorefiles.txt.gz')) feather conversion complete
pgscatalog.match.lib._match.preprocess: 2024-08-07 10:46:45 DEBUG    Complementing column effect_allele
pgscatalog.match.lib._match.preprocess: 2024-08-07 10:46:45 DEBUG    Complementing column other_allele
pgscatalog.match.lib.variantframe: 2024-08-07 10:46:45 DEBUG    Converting VariantFrame(path='GRCh37_sample1228_ALL.pvar.zst', dataset='sample1228', chrom=None, cleanup=True, tmpdir=PosixPath('/home/ubuntu/user/rundir/test/sample_1228/work/5d/058b620cca1d372ae4d78f7cddea16/tmp')) to feather format
pgscatalog.match.lib.variantframe: 2024-08-07 10:46:58 DEBUG    VariantFrame(path='GRCh37_sample1228_ALL.pvar.zst', dataset='sample1228', chrom=None, cleanup=True, tmpdir=PosixPath('/home/ubuntu/user/rundir/test/sample_1228/work/5d/058b620cca1d372ae4d78f7cddea16/tmp')) feather conversion complete
pgscatalog.match.lib._match.preprocess: 2024-08-07 10:46:58 DEBUG    Filtering target to include chromosomes 1 - 22, X, Y
pgscatalog.match.lib._match.preprocess: 2024-08-07 10:47:01 DEBUG    No multiallelic variants detected
pgscatalog.match.lib._match.match: 2024-08-07 10:47:01 DEBUG    Getting matches for scores with effect allele and other allele
pgscatalog.match.lib._match.match: 2024-08-07 10:47:01 DEBUG    Matching strategy: refalt
pgscatalog.match.lib._match.match: 2024-08-07 10:47:01 DEBUG    Matching strategy: altref
pgscatalog.match.lib._match.match: 2024-08-07 10:47:01 DEBUG    Matching strategy: refalt_flip
pgscatalog.match.lib._match.match: 2024-08-07 10:47:01 DEBUG    Matching strategy: altref_flip
pgscatalog.match.lib._match.match: 2024-08-07 10:47:01 DEBUG    Getting matches for scores with effect allele only
pgscatalog.match.lib._match.match: 2024-08-07 10:47:01 DEBUG    Matching strategy: no_oa_ref
pgscatalog.match.lib._match.match: 2024-08-07 10:47:01 DEBUG    Matching strategy: no_oa_alt
pgscatalog.match.lib._match.match: 2024-08-07 10:47:01 DEBUG    Matching strategy: no_oa_ref_flip
pgscatalog.match.lib._match.match: 2024-08-07 10:47:01 DEBUG    Matching strategy: no_oa_alt_flip
```

### System information

Singularity, Ubuntu, pgsc_calc v2.0.0-beta.2

**Comment by nebfield** [comment]
Thanks for the bug report. I've encountered this a few times before when Nextflow's `-resume` gets a bit confused. Does the problem still happen if:

1. You run the workflow successfully with the [`--genotypes_cache` parameter set to a directory outside of `work/`](https://pgsc-calc.readthedocs.io/en/latest/how-to/cache.html)
2. `rm -r work` 
3. You run the workflow again using new scores but with `--genotypes_cache` as described in step 1

**Comment by Fiwx** [comment]
Thanks, I will try this now. Some more info:

- I ran this in a new machine which had never ran pgsc_calc before, so I would assume that nothing was cached from a previous run, and that there would be no work directory at the start of the run
- I did not set genotypes_cache

**Comment by Fiwx** [comment]
@nebfield I tried your suggestions, but the same FileExistsError occurred when I ran .command.run.

```
[3b/abb3c4] PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_COMBINE [ 66%] 2 of 3, failed: 2, retries: 2
```

```
  pgscatalog.match.lib._match.filter: 2024-08-08 12:45:15 DEBUG    Calculating overlap between target genome and scoring file
  .command.sh: line 9:  1456 Killed                  pgscatalog-matchmerge --dataset sample1006 --scorefile scorefiles.txt.gz --matches *.ipc.zst --min_overlap 0.0 --filter_IDs filter_ids.txt.gz --outdir $PWD --combined -v
```

```
ERROR ~ Error executing process > 'PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_COMBINE (user10001file8265yearofbirthunknownsexunknown)'

Caused by:
  Process `PGSCATALOG_PGSCCALC:PGSCCALC:MATCH:MATCH_COMBINE (user10001file8265yearofbirthunknownsexunknown)` terminated with an error exit status (137)


Command executed:

  # filter match candidates to intersect with reference:
  # omit multi-allelic variants in reference because these will cause errors with relabelling!...
  # ... unclear whether we should remove them from target with (9th column) as well?
  awk 'NR > 1 && $6 == "False" { print $7 } ' <(zcat user10001file8265yearofbirthunknownsexunknown_ALL_matched.txt.gz) | gzip > filter_ids.txt.gz

  export POLARS_MAX_THREADS=2

  pgscatalog-matchmerge                          --dataset user10001file8265yearofbirthunknownsexunknown             --scorefile scorefiles.txt.gz  --matches *.ipc.zst             --min_overlap 0.0                                       --filter_IDs filter_ids.txt.gz             --outdir $PWD               --combined             -v

  cat <<-END_VERSIONS > versions.yml
  MATCH_COMBINE:
      pgscatalog.match: $(echo $(python -c 'import pgscatalog.match; print(pgscatalog.match.__version__)'))
  END_VERSIONS
```

**Comment by Fiwx** [comment]
I replicated this on a variety of versions, including the dev branch, so it is not specific to v2.0.0-beta.2.

**Comment by smlmbrt** [comment]
@Fiwx, sometimes you have to delete the specific failed job's work directory that failed to get it to resume when there's a FileExistsError. Also it seems like the 137 error might have originally been out of memory?

**Comment by Fiwx** [comment]
I don't know why the FileExistsError happened, and deleting the work directory didn't change the behavior. However, the reason why it failed originally was indeed memory. I increased the memory from 16 GB to 32 GB and the error did not occur.

The issue occurs when using:
- 16 GB RAM, _and_
- Many (30+) scorefiles

The issue does not occur when using:
- 32 GB RAM, _or_
- Fewer (10+) scorefiles

It would be nice (though perhaps unfeasible):
- Have error display "out of memory" (I don't know why I didn't think to look up Nextflow error 137)
- Do less parallelization on the matching step if there is not enough RAM, so it is possible to run on 16 GB RAM.

**Comment by smlmbrt** [comment]
We tried to make the error codes from within the pipeline (e.g. data/formatting issues) more specific for debugging, it's not really possible for us to debug the error codes from docker/nextflow as those will be cluster/setup-dependant. The easiest way to debug those is to google the "`[error code] + [docker or nextflow, etc]`". 

We'll look into reducing the memory footprint of the matching, but to some extent this is determined by the number of variants in your target sample and the number of variants in your scoring files. You can reduce the max memory needed by splitting your data by chromosome, and as your noted by reducing the number of scores you're calculating at once.

**Comment by Fiwx** [comment]
Thank you. One idea is to read ScoringFileFrame in chunks, with an iterator that yields chunks of data that get_match_candidates uses instead of score_df. However, it is probably not worth it to implement since there may be other memory bottlenecks and it seems like this is a rare error.
