### ISSUE TITLE
starting with gVCF?

### ISSUE THREAD

**Issue by moe1619** [PGScatalog/pgsc_calc#49]
Hello, I'm new to calculating PRSs. If I have gVCFs from WGS, what is the best way to create the VCF necessary for input? Should I get the SNPs needed for the relevant PRS and get variant or reference calls for those SNPs?

Thanks very much for your help.

**Comment by moe1619** [comment]
I should add, if you have a suggestion for starting with gVCF, I'll take that. If not, I can call the specific SNPs relevant for the PRS from the BAM. 

Also happy to take other suggestions. Thanks!

**Comment by smlmbrt** [comment]
I'm going to take a look at the specifications for that format. Usually the VCFs that the pipeline would receive are the ones that are output from genotype imputation (e.g. by the Michigan or TopMed imputation servers). In theory a VCF for WGS could be input as-is, but the variant matching statistics would be incorrect because our pipeline would consider them as missing if they are homozygous REF (e.g. not in the VCF).

**Comment by moe1619** [comment]
If re-calling from BAMs, I would use something like GATKs --output-mode EMIT_ALL_ACTIVE_SITES so that I would get both reference and variant calls at the sites. Does that make sense?

**Comment by moe1619** [comment]
And thanks again for your help

**Comment by moe1619** [comment]
Running on a Mac

created VCF from WGS BAMs aligned to grch37

```
  $gatk_path --java-options "-Xmx4G" HaplotypeCaller \
  -R /PATHhs37d5.fa \
  -L output/PRS_snp_positions.list \
  -I $bam_path -ip 2 \
  -O $vcf_for_prs -ERC BP_RESOLUTION
```

ran nextflow pipeline

```
nextflow run pgscatalog/pgsc_calc -r dev -profile docker --pgs_id PGS000043 --input ./input/samplesheet.csv --target_build GRCh37
```
get the following error

```
executor >  local (5)
[63/d5fe51] process > PGSCATALOG_PGSCALC:PGSCALC:DOWNLOAD_SCOREFILES ([pgs_id:PGS000043, pgp_id:, trait_efo:]) [100%] 1 of 1 ✔
[62/360a88] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)                [100%] 1 of 1 ✔
[f8/bf99e0] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:COMBINE_SCOREFILES (1)                            [100%] 1 of 1 ✔
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM                             -
[1f/d3f6c2] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELPVAR (test chromosome 1-22)     [100%] 1 of 1 ✔
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_VCF                                    -
[bf/8261df] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:MATCH_VARIANTS (test)                         [  0%] 0 of 1
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:PLINK2_SCORE                                      -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:SCORE_REPORT                                      -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:DUMPSOFTWAREVERSIONS                                          -
Staging foreign file: https://gitlab.ebi.ac.uk/nebfield/test-datasets/-/raw/master/pgsc_calc/reference_data/pgsc_calc_ref.sqlar
Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:MATCH_VARIANTS (test)'

Caused by:
  Process `PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:MATCH_VARIANTS (test)` terminated with an error exit status (1)

Command executed:

  export POLARS_MAX_THREADS=2
  
  match_variants         --min_overlap 0.75         --dataset test         --scorefile scorefiles.txt.gz         --target "$PWD/*.vars"         --split                                    --outdir $PWD         -v
  
  cat <<-END_VERSIONS > versions.yml
  MATCH_VARIANTS:
      pgscatalog_utils: $(echo $(python -c 'import pgscatalog_utils; print(pgscatalog_utils.__version__)'))
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  pgscatalog_utils.match.label: 2022-09-16 02:16:53 DEBUG    Labelling all duplicates with exclude flag
  pgscatalog_utils.match.label: 2022-09-16 02:16:53 DEBUG    Labelling ambiguous variants
  pgscatalog_utils.match.preprocess: 2022-09-16 02:16:53 DEBUG    Complementing column REF
  pgscatalog_utils.match.label: 2022-09-16 02:16:53 DEBUG    Labelling ambiguous variants with exclude flag
  pgscatalog_utils.match.read: 2022-09-16 02:16:53 DEBUG    Detecting target file format
  pgscatalog_utils.match.read: 2022-09-16 02:16:53 DEBUG    pvar format detected
  pgscatalog_utils.match.read: 2022-09-16 02:16:53 DEBUG    Scanning target genome for chromosome 1
  pgscatalog_utils.match.preprocess: 2022-09-16 02:16:53 DEBUG    Multiallelic variants detected
  pgscatalog_utils.match.preprocess: 2022-09-16 02:16:53 DEBUG    Dropping multiallelic variants
  pgscatalog_utils.match.match_variants: 2022-09-16 02:16:53 DEBUG    Matching chromosome 1
executor >  local (5)
[63/d5fe51] process > PGSCATALOG_PGSCALC:PGSCALC:DOWNLOAD_SCOREFILES ([pgs_id:PGS000043, pgp_id:, trait_efo:]) [100%] 1 of 1 ✔
[62/360a88] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (samplesheet.csv)                [100%] 1 of 1 ✔
[f8/bf99e0] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:COMBINE_SCOREFILES (1)                            [100%] 1 of 1 ✔
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM                             -
[1f/d3f6c2] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELPVAR (test chromosome 1-22)     [100%] 1 of 1 ✔
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_VCF                                    -
[bf/8261df] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:MATCH_VARIANTS (test)                         [100%] 1 of 1, failed: 1 ✘
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:PLINK2_SCORE                                      -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:SCORE_REPORT                                      -
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:DUMPSOFTWAREVERSIONS                                          -
Staging foreign file: https://gitlab.ebi.ac.uk/nebfield/test-datasets/-/raw/master/pgsc_calc/reference_data/pgsc_calc_ref.sqlar
Execution cancelled -- Finishing pending tasks before exit
Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:MATCH_VARIANTS (test)'

Caused by:
  Process `PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:MATCH_VARIANTS (test)` terminated with an error exit status (1)

Command executed:

  export POLARS_MAX_THREADS=2
  
  match_variants         --min_overlap 0.75         --dataset test         --scorefile scorefiles.txt.gz         --target "$PWD/*.vars"         --split                                    --outdir $PWD         -v
  
  cat <<-END_VERSIONS > versions.yml
  MATCH_VARIANTS:
      pgscatalog_utils: $(echo $(python -c 'import pgscatalog_utils; print(pgscatalog_utils.__version__)'))
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  pgscatalog_utils.match.label: 2022-09-16 02:16:53 DEBUG    Labelling all duplicates with exclude flag
  pgscatalog_utils.match.label: 2022-09-16 02:16:53 DEBUG    Labelling ambiguous variants
  pgscatalog_utils.match.preprocess: 2022-09-16 02:16:53 DEBUG    Complementing column REF
  pgscatalog_utils.match.label: 2022-09-16 02:16:53 DEBUG    Labelling ambiguous variants with exclude flag
  pgscatalog_utils.match.read: 2022-09-16 02:16:53 DEBUG    Detecting target file format
  pgscatalog_utils.match.read: 2022-09-16 02:16:53 DEBUG    pvar format detected
  pgscatalog_utils.match.read: 2022-09-16 02:16:53 DEBUG    Scanning target genome for chromosome 1
  pgscatalog_utils.match.preprocess: 2022-09-16 02:16:53 DEBUG    Multiallelic variants detected
  pgscatalog_utils.match.preprocess: 2022-09-16 02:16:53 DEBUG    Dropping multiallelic variants
  pgscatalog_utils.match.match_variants: 2022-09-16 02:16:53 DEBUG    Matching chromosome 1
  pgscatalog_utils.match.match: 2022-09-16 02:16:53 DEBUG    Getting matches for scores with effect allele and other allele
  pgscatalog_utils.match.match: 2022-09-16 02:16:53 DEBUG    Matching strategy: refalt
  pgscatalog_utils.match.match: 2022-09-16 02:16:53 DEBUG    Matching strategy: altref
  pgscatalog_utils.match.match: 2022-09-16 02:16:53 DEBUG    Matching strategy: refalt_flip
  pgscatalog_utils.match.match: 2022-09-16 02:16:53 DEBUG    Matching strategy: altref_flip
  pgscatalog_utils.match.label: 2022-09-16 02:16:53 DEBUG    Labelling best match type (refalt > altref > ...)
  pgscatalog_utils.match.label: 2022-09-16 02:16:53 DEBUG    Labelling duplicated best match: keeping first instance as best_match = True
  pgscatalog_utils.match.label: 2022-09-16 02:16:53 DEBUG    Labelling multiple scoring file lines (accession/row_nr) that best_match to the same variant
  pgscatalog_utils.match.label: 2022-09-16 02:16:53 DEBUG    Labelling all duplicates with exclude flag
  pgscatalog_utils.match.label: 2022-09-16 02:16:53 DEBUG    Labelling ambiguous variants
  pgscatalog_utils.match.preprocess: 2022-09-16 02:16:53 DEBUG    Complementing column REF
  pgscatalog_utils.match.label: 2022-09-16 02:16:53 DEBUG    Labelling ambiguous variants with exclude flag
  pgscatalog_utils.match.read: 2022-09-16 02:16:53 DEBUG    Detecting target file format
  pgscatalog_utils.match.read: 2022-09-16 02:16:53 DEBUG    pvar format detected
  pgscatalog_utils.match.read: 2022-09-16 02:16:53 DEBUG    Scanning target genome for chromosome 9
  pgscatalog_utils.match.preprocess: 2022-09-16 02:16:53 DEBUG    Multiallelic variants detected
  pgscatalog_utils.match.preprocess: 2022-09-16 02:16:53 DEBUG    Dropping multiallelic variants
  pgscatalog_utils.match.match_variants: 2022-09-16 02:16:53 DEBUG    Matching chromosome 9
  pgscatalog_utils.match.match: 2022-09-16 02:16:53 DEBUG    Getting matches for scores with effect allele and other allele
  pgscatalog_utils.match.match: 2022-09-16 02:16:53 DEBUG    Matching strategy: refalt
  pgscatalog_utils.match.match: 2022-09-16 02:16:53 DEBUG    Matching strategy: altref
  pgscatalog_utils.match.match: 2022-09-16 02:16:53 DEBUG    Matching strategy: refalt_flip
  pgscatalog_utils.match.match: 2022-09-16 02:16:53 DEBUG    Matching strategy: altref_flip
  pgscatalog_utils.match.label: 2022-09-16 02:16:53 DEBUG    Labelling best match type (refalt > altref > ...)
  pgscatalog_utils.match.label: 2022-09-16 02:16:53 DEBUG    Labelling duplicated best match: keeping first instance as best_match = True
  pgscatalog_utils.match.label: 2022-09-16 02:16:53 DEBUG    Labelling multiple scoring file lines (accession/row_nr) that best_match to the same variant
  pgscatalog_utils.match.label: 2022-09-16 02:16:53 DEBUG    Labelling all duplicates with exclude flag
  pgscatalog_utils.match.label: 2022-09-16 02:16:53 DEBUG    Labelling ambiguous variants
  pgscatalog_utils.match.preprocess: 2022-09-16 02:16:53 DEBUG    Complementing column REF
  pgscatalog_utils.match.label: 2022-09-16 02:16:53 DEBUG    Labelling ambiguous variants with exclude flag
  pgscatalog_utils.match.filter: 2022-09-16 02:16:53 DEBUG    Filtering variants with exclude flag
  pgscatalog_utils.match.filter: 2022-09-16 02:16:53 DEBUG    Calculating overlap between target genome and scoring file
  pgscatalog_utils.match.filter: 2022-09-16 02:16:53 ERROR    Score PGS000043_hmPOS_GRCh37 fails minimum matching threshold (0.00% variants match)
  pgscatalog_utils.match.match_variants: 2022-09-16 02:16:53 ERROR    Error: no target variants match any variants in scoring files
  Traceback (most recent call last):
    File "/usr/local/bin/match_variants", line 8, in <module>
      sys.exit(match_variants())
    File "/usr/local/lib/python3.10/site-packages/pgscatalog_utils/match/match_variants.py", line 61, in match_variants
      raise Exception
  Exception

Work dir:
  /PATH/bf/8261df187fc9f3a16d1e8cd216ad71

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`


ERROR: No scores calculated!
```

Not sure why I'm not matching any variants.

Thanks.

**Comment by moe1619** [comment]
Actually, I see some issues in my VCF. I'l update and get back to you. Thanks!

**Comment by moe1619** [comment]
OK, I can get the variant sites to match but I cannot get the reference sites to match. What is the correct format in the input file for a position when the site is homozygous reference?

Thanks,
Josh

**Comment by moe1619** [comment]
I think you can close this issue if you'd like. I'm making more progress on essentially the same question inanother issue I opened

https://github.com/PGScatalog/pgsc_calc/issues/50

Thanks
