### ISSUE TITLE
ThreadPoolBuildError

### ISSUE THREAD

**Issue by wangbaonan** [PGScatalog/pgsc_calc#69]
Dear team,
when running v1.3.0 i got this error(see below), But the same command I once ran successfully, do you know how to fix it?

`Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:MATCH_VARIANTS (NGS1926_Han_2Target chromosome 20)'

Caused by:
  Process `PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:MATCH_VARIANTS (NGS1926_Han_2Target chromosome 20)` terminated with an error exit status (1)

Command executed:

  export POLARS_MAX_THREADS=2

  match_variants                  --dataset NGS1926_Han_2Target         --scorefile scorefiles.txt.gz         --target vcf_NGS1926_Han_2Target_20.pvar.zst         --only_match         --chrom 20                                    --outdir $PWD         -n 2         -v

  cat <<-END_VERSIONS > versions.yml
  MATCH_VARIANTS:
      pgscatalog_utils: $(echo $(python -c 'import pgscatalog_utils; print(pgscatalog_utils.__version__)'))
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  root: 2022-12-09 10:20:53 DEBUG    Verbose logging enabled
  pgscatalog_utils.config: 2022-12-09 10:20:53 DEBUG    Using 2 threads to read CSVs
  pgscatalog_utils.config: 2022-12-09 10:20:53 DEBUG    polars threadpool size: 2
  pgscatalog_utils.config: 2022-12-09 10:20:53 DEBUG    Temporary directory set up: /tmp/nxf.nMQxqmuesI/work_match/tmpnhdcx05y
  pgscatalog_utils.match.read: 2022-12-09 10:20:53 DEBUG    Reading scorefile
  pgscatalog_utils.match.read: 2022-12-09 10:20:53 DEBUG    --chrom set, filtering scoring file to chromosome 20
  pgscatalog_utils.match.preprocess: 2022-12-09 10:20:53 DEBUG    Complementing column effect_allele
  pgscatalog_utils.match.preprocess: 2022-12-09 10:20:53 DEBUG    Complementing column other_allele
  pgscatalog_utils.match.match_variants: 2022-12-09 10:20:53 DEBUG    Match mode: single
  pgscatalog_utils.target: 2022-12-09 10:20:53 DEBUG    Scanning header to get file format
  pgscatalog_utils.target: 2022-12-09 10:20:53 ERROR    Can't open target as a text file, so trying to read zstd compressed binary file
  pgscatalog_utils.target: 2022-12-09 10:20:53 DEBUG    Scanning header to get file format
  pgscatalog_utils.target: 2022-12-09 10:20:53 DEBUG    pvar format detected
  pgscatalog_utils.match.read: 2022-12-09 10:20:53 DEBUG    Reading all target data complete
  pgscatalog_utils.target: 2022-12-09 10:20:53 DEBUG    Reading compressed chunks from target genome (slower, lower RAM usage)
  pgscatalog_utils.target: 2022-12-09 10:20:53 DEBUG    Started reading zstd compressed data
  pgscatalog_utils.target: 2022-12-09 10:20:55 DEBUG    3 chunks
  pgscatalog_utils.match.preprocess: 2022-12-09 10:20:55 DEBUG    Filtering target to include chromosomes 1 - 22, X, Y
  thread '<unnamed>' panicked at 'The global thread pool has not been initialized.: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.3/src/registry.rs:170:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  Traceback (most recent call last):
    File "/venv/bin/match_variants", line 8, in <module>
      sys.exit(match_variants())
    File "/venv/lib/python3.10/site-packages/pgscatalog_utils/match/match_variants.py", line 54, in match_variants
      matches: list[list[pl.LazyFrame]] = _fast_match(target_paths, scorefile, low_memory)
    File "/venv/lib/python3.10/site-packages/pgscatalog_utils/match/match_variants.py", line 133, in _fast_match
      target: pl.LazyFrame = read_target(paths=target_paths, low_memory=low_memory)
    File "/venv/lib/python3.10/site-packages/pgscatalog_utils/match/read.py", line 21, in read_target
      .pipe(annotate_multiallelic)
    File "/venv/lib/python3.10/site-packages/polars/internals/lazyframe/frame.py", line 568, in pipe
      return func(self, *args, **kwargs)
    File "/venv/lib/python3.10/site-packages/pgscatalog_utils/match/preprocess.py", line 49, in annotate_multiallelic
      if (df.select('is_multiallelic').unique().collect().get_column('is_multiallelic')).any():
    File "/venv/lib/python3.10/site-packages/polars/internals/lazyframe/frame.py", line 937, in collect
      return pli.wrap_df(ldf.collect())
  pyo3_runtime.PanicException: The global thread pool has not been initialized.: ThreadPoolBuildError { kind: IOError(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }) }
  pgscatalog_utils.match.tempdir: 2022-12-09 10:20:55 DEBUG    Cleaning up tempdir path <TemporaryDirectory '/tmp/nxf.nMQxqmuesI/work_match/tmpnhdcx05y'>

Work dir:
  /home/pogadmin/dev_PGP/05_pgsc_calc/07_NGS1926_Han_pgsc_calc/work/21/162a1579a2faa90110c035120f875e

Tip: you can replicate the issue by changing to the process work dir and entering the command `

Best,
Wang

**Comment by nebfield** [comment]
Thanks for reporting the issue.

Unfortunately I've never seen this error before. Can you try rerunning the pipeline with the `-resume` parameter to see if it was a temporary problem? If the error keeps happening could you please let me know:

* Which profile you use (docker, singularity, or conda) to run `pgsc_calc`
* What OS you're using 
* The full nextflow command you use

**Comment by smlmbrt** [comment]
Related to #82
